parameters:
#    utah_spj_awards.example.class: UtahSpj\AwardsBundle\Example

services:
#    utah_spj_awards.example:
#        class: %utah_spj_awards.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
